name: electricilies-backend

services:
  db:
    image: paradedb/paradedb:17-v0.20.0
    environment:
      POSTGRES_USER: ${DB_USERNAME:-electricilies}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-electricilies}
      POSTGRES_DB: ${DB_DATABASE:-postgres}
      PGDATA: /data/postgres
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - db:/data/postgres
      - ./volume/init.sql:/docker-entrypoint-initdb.d/00-init.sql
      - ./volume/schema.sql:/docker-entrypoint-initdb.d/10-schema.sql
      - ./volume/trigger.sql:/docker-entrypoint-initdb.d/11-trigger.sql
      - ./volume/seed.sql:/docker-entrypoint-initdb.d/20-seed.sql
      - ./volume/paradedb-index.sql:/docker-entrypoint-initdb.d/30-paradedb-index.sql
    healthcheck:
      test:
        [CMD, pg_isready, -U, "${DB_USERNAME:-electricilies}", -h, localhost]
    restart: unless-stopped

  keycloak-db:
    image: postgres:18.0-alpine3.22
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - keycloak-db:/data/postgres
    healthcheck:
      test: [CMD, pg_isready, -U, postgres, -h, localhost]
    restart: unless-stopped

  keycloak:
    image: keycloak/keycloak:26.4.4
    command: start-dev
    environment:
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: false
      KC_HTTP_PORT: ${KC_HTTP_PORT:-8081}
      KC_HTTP_MANAGEMENT_PORT: ${KC_HTTP_MANAGEMENT_PORT:-8082}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN:-electricilies}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD:-electricilies}
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    ports:
      - ${KC_HTTP_PORT:-8081}:${KC_HTTP_PORT:-8081}
      - ${KC_HTTP_MANAGEMENT_PORT:-8082}:${KC_HTTP_MANAGEMENT_PORT:-8082}
    depends_on:
      - keycloak-db
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    ports:
      - 9000:9000
      - 9001:9001
    command:
      - server
      - /data
      - --console-address=:9001
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-electricilies}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-electricilies}
    volumes:
      - minio:/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9000/minio/health/live
      start_period: 5s

  redis:
    image: redis:8.2.2-alpine3.22
    command:
      - redis-server
      - --save
      - "60"
      - "1"
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    restart: unless-stopped
    profiles:
      - deploy

volumes:
  db:
  minio:
  redis:
  keycloak-db:
